#服务器
server:
  port: 8888


spring:
    #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb
    username: root
    password: alex0425
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置
mybatis:
  typeAliasesPackage: com.example.mybaitsxml.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml

#  configuration:
#    map-underscore-to-camel-case: true

